# Generated by Django 4.2.2 on 2023-10-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custermer',
            new_name='customer',
        ),
    ]
